Algoritmo "semnome"
// desenvolver um programa que exiba os numeros em ordem descrescente
//de 100 á 1.
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("exibindo os números de forma descrescente de 100 á 1")
contador <- 100
enquanto ( contador >= 1 ) faca
         escreval (contador)
         contador <- contador -1
fimenquanto
         

Fimalgoritmo