Algoritmo "semnome"
// fazer um programa de exiba os numeros de 1 a 100
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("exibindo os números de 1 a 100")
contador <- 1
enquanto ( contador <= 100 ) faca
          escreval ( contador )
          contador <- contador + 1
fimenquanto
         


Fimalgoritmo