Algoritmo "semnome"
// desenvolver um programa que apresente os quadrados dos números
//inteiros de 15 á 200
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("exibindo os números ao quadrado de 15 á 200")
para numero de 15 ate 200 faca
     escreval ( " o numéro ao quadrado de ", numero, " é ", numero * numero )
fimpara

Fimalgoritmo