Algoritmo "semnome"
// desenvolver um programa que apresente o valor da soma dos cem
//primeiros números inteiros (1+2+3+4+5+6+7+... 99+ 100)
Var
// Seção de Declarações das variáveis 
numero, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("exibindo a soma dos números inteiros de 1 á 100")
soma <- 0
numero <- 1
enquanto numero  de 1 ate 100 faca
     soma <- + numero
fimenquanto

Fimalgoritmo